### PR TITLE
Second milestone

### PR DESCRIPTION
**Pull request by ReemMohamedAbdelfatah**
For the second milestone of the Vet Clinic database, I

- Add a column species of type string to the animal table.
- Insert the given data of 7 new animals. The total becomes 11.
- Use transactions to delete and modify data in the animal table.
- Perform the given queries.

**Screenshots of table modification**
https://drive.google.com/file/d/1RR6l_j_G7Dq_FDF9hONDvgfhKUrssECh/view?usp=share_link

**Screenshots of actions results**
https://drive.google.com/file/d/1wntmxCfJYI0AX8-yyvVmJReMktL7X9TE/view?usp=share_link
https://drive.google.com/file/d/1uUzkrnCS50w_xOWLCyEK6ETpQeRAf6Q1/view?usp=share_link
https://drive.google.com/file/d/1Qhz75M9FABYKTxgrysJrwCNQhTfNvBjY/view?usp=share_link
https://drive.google.com/file/d/1DVSXFtdUuC2FoZU4h9zZd2LIHvVRDRRr/view?usp=share_link
https://drive.google.com/file/d/1EjYFoaE2JE_xD-T1r9qNSkorlZuLQuXu/view?usp=share_link
https://drive.google.com/file/d/1xKFPSk9CI97rQq6z_Vfum7amKqwNsXiy/view?usp=share_link
https://drive.google.com/file/d/1LaLfA0YdJeTVw-r5g6m3AwYiijSiWY22/view?usp=share_link

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @ReemMohamedAbdelfatah       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 


## Highlights   
- Good use SQL queries ✔️   

# Required Changes  🌵 

- [x] You made some impressive implementations based on the project requirements, but there are  more you need to adjust

- [ ] Instead of querying the whole table, let's optimize it and query just the `species`. 
image

## Sample query:
 ```
 SELECT species from animals; -- verify that change was made
   ROLLBACK;

   SELECT species from animals; -- verify that change was undone
```
- [ ] The task in the query below is to update the `animals` table by setting the `species` column to `pokemon` for all `animals` that don't have species already set. Kindly refactor it as spcified.
## Code:
image
- Sample solution:
- ``UPDATE animals SET species = 'pokemon' WHERE species IS NULL;``

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @ReemMohamedAbdelfatah       👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 


## Highlights   
- Good use SQL queries ✔️   

# Required Changes  🌵 

- [x] You made some impressive implementations based on the project requirements, but there are  more you need to adjust

- [x] Instead of querying the whole table, let's optimize it and query just the `species`. 
image

## Sample query:
 ```
 SELECT species from animals; -- verify that change was made
   ROLLBACK;

   SELECT species from animals; -- verify that change was undone
```
- [x] The task in the query below is to update the `animals` table by setting the `species` column to `pokemon` for all `animals` that don't have species already set. Kindly refactor it as spcified.
## Code:
image
- Sample solution:
- ``UPDATE animals SET species = 'pokemon' WHERE species IS NULL;``

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ReemMohamedAbdelfatah** [comment]
Done! 👌

**Review by nahnahdev — APPROVED** [review]
## Project Status: APPROVED :green_circle: 
Hi @ReemMohamedAbdelfatah , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


## Highlights
- All requested changes implemented :wink: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
